### ISSUE TITLE
Needs a 64x64 and 128x128 icon

### ISSUE THREAD

**Issue by nedrichards** [flathub/org.develz.Crawl#1]
In order to show up on the [apps page](https://beta.flathub.org/apps) this needs at least a 64x64 icon. The largest icon this currently contains is 48px.

**Comment by arteymix** [comment]
I'll rescale the logo and preserve the pixel-art look. I see that we have `convert` available in the sandboxed environment, so it will just be part of the build.

One side question: can we have multiple versions? People tend to play with different minor releases of the game, especially on the Web version

**Comment by nedrichards** [comment]
Multiple versions of the icon? or the app? If it's the icon, you can (and should) offer multiple sizes but you can only export one icon name (with the name of your app)

If it's the app, you could consider the ostree repo that flatpak uses to be like a a git repo. There's one branch that's offered (stable) and all the releases you make are available within it, you just need to select them. The flatpak tool and UIs like GNOME Software currently railroad you down a path of 'always the latest' but there's no special reason why that has to be true forever - so that's more of a question for flatpak and gnome software than flathub per se.

**Comment by arteymix** [comment]
I meant for the application.

By the way, I cannot call `convert` during the post-installation step although it's available via `--command=sh` when I run the flatpak.

**Comment by nedrichards** [comment]
Resolved by https://github.com/flathub/org.develz.Crawl/commit/d9a8300d683ed0d7c0e4da44a85f164aa2e8d90a
