### ISSUE TITLE
Update to 0.28

### ISSUE THREAD

**Issue by TheSamsai** [flathub/org.develz.Crawl#13]
Version 0.28 has been released and it would be nice to see the Flathub version updated to that version.

https://github.com/crawl/crawl/releases/tag/0.28.0

**Comment by arteymix** [comment]
I'm currently updating it. I'll also update the freedesktop platform to 21.08.

**Comment by arteymix** [comment]
Hmm, I tried to update PyYAML, but I think it changes its requirements as of 5.4. I'll open an issue regarding this when I get more information.

**Comment by arteymix** [comment]
Fixed in 6c4ea777fa32622309fbda5dfed7f9d746657f2a

**Comment by TheSamsai** [comment]
Thanks!

**Comment by arteymix** [comment]
@TheSamsai 

I ran into a bug when updating that I reported here https://github.com/crawl/crawl/issues/2414 It seems to be related to my save, not the Flatpak itself. Let me know if everything works as expected.

**Comment by TheSamsai** [comment]
@arteymix I don't have existing saves and I don't even know if DCSS considers saves to be valid between versions. What I can say is that the 0.28 version on Flathub is working for me for new saves at the very least.
