### ISSUE TITLE
Crawl 0.29.1

### ISSUE THREAD

**Issue by robertxgray** [flathub/org.develz.Crawl#19]
Crawl 0.29.1 bugfix release is available: https://github.com/crawl/crawl/releases/tag/0.29.1

- 20+ bug and documentation fixes
- Improvements to linux packaging support infrastructure

Those improvements are likely to break your build, sorry. But I'm here to help.

The file `debian/crawl-tiles.desktop` no longer exists. It's in a different path but you're not supposed to use it. Instead you should be using this new build target (can be combined with make install):
`make prefix=/app XDG_NAME=org.develz.Crawl install-xdg-data`

This will create the following files:

- /app/share/icons/hicolor/32x32/apps/org.develz.Crawl.png
- /app/share/icons/hicolor/48x48/apps/org.develz.Crawl.png
- /app/share/icons/hicolor/512x512/apps/org.develz.Crawl.png
- /app/share/icons/hicolor/scalable/apps/org.develz.Crawl.svg
- /app/share/applications/org.develz.Crawl.desktop
- /app/share/metainfo/org.develz.Crawl.appdata.xml

The desktop and appdata files were made for distributors who provide both builds of the game (console and tiles) in mind. You'll probably want to adapt their contents to your needs even though we mostly copied yours. Note you're missing the developer name.

`<developer_name>The Dungeon Crawl Stone Soup Devteam</developer_name>`

The appdata isn't created in the appdata folder because the `linuxdeploy` tool used to create AppImages for Crawl didn't like it the last time I checked it. This may change in the future.

More info here: https://github.com/crawl/crawl/pull/2188

**Comment by arteymix** [comment]
Hello @robertxgray! Would you consider preparing a PR for all these adjustments?

**Comment by robertxgray** [comment]
Sure, just give me some time because I never built a Flatpak before.
