### ISSUE TITLE
Version 0.24.0 is now available

### ISSUE THREAD

**Issue by Kirtai** [flathub/org.develz.Crawl#6]
This has a new release 0.24.0, though for some reason the github releases page is showing 0.23.0 as the latest release.

**Comment by arteymix** [comment]
I'm rebuilding the whole thing on freedesktop 19.08 SDK and will subsequently update Crawl to 0.24.

**Comment by Kirtai** [comment]
That's great :)

**Comment by arteymix** [comment]
Discussion will continue on #7.
